language: rust
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libssl-dev
before_install:
- openssl aes-256-cbc -K $encrypted_b396eeddcdb5_key -iv $encrypted_b396eeddcdb5_iv
  -in .spotify_token_cache.json.enc -out .spotify_token_cache.json -d
- curl -L https://github.com/mozilla/grcov/releases/download/v0.4.1/grcov-linux-x86_64.tar.bz2
  | tar jxf -
cache: cargo
matrix:
  include:
  - os: linux
    rust: nightly
before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin -f
  fi
script:
- cargo clean
- cargo build
- cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
     cargo build
     cargo tarpaulin --out Xml
     bash <(curl -s https://codecov.io/bash)
  fi
